# Generated by Django 4.1.4 on 2023-06-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_author_email_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_name",
            field=models.ImageField(null=True, upload_to="posts"),
        ),
    ]
