# Generated by Django 4.1.4 on 2023-06-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_alter_post_image_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image_name",
            new_name="image",
        ),
    ]
